# there are algorithm and method specific parameters see readme for details
# method and algorithm are mandatory if others are left blank default values are assumed

method: backgroud_remove
algorithm: MOG2
method_parameters:
   detectShadows: false
   history: 10
apply_parameters:
   learningRate: 0.5
invert_frame: false
invert_mask: false
video:
   write: true
   size:
      width: 3
      height: 3
   FPS: 10
   periodicity: 10