# there are algorithm and method specific parameters see readme for details
# method and algorithm are mandatory if others are left blank default values are assumed

method: background #
algorithm: MOG2
method_parameters:
   detectShadows: false
   history: 10
#TODO learning rate for background subtraction and other params for optical flow
invert_frame: false
invert_mask: false