# this file specifies pipeline parameters there are
# too many for them to be a command line argument.
# some of the features are not fully developed yet.
frames:
  return_denoized: true
  disk_size: 2
  invert: false
subtractor:
  algorithm: KNN
  learningRate: 0.7
calculate:
  - area #mask area
  - bbox_area # area of the bounding box
  - convex_area # area of the convex hull
  - eccentricity # how eliptical is the mask
  - extent # area of bounding box/area of mask
  - local_centroid # centre of mass of the mask
  - major_axis_length # of the bounding ellipse
  - minor_axis_length # of the bounding ellipse
  - perimeter # of the mask
  - solidity # how rectangular is the mask
  - weighted_local_centroid
video:
  write: true
  what:
    - overlay
    - mask
    - frame
  periodicity: 20
  FPS: 10
  size:
    width: 3
    height: 3