# this file specifies pipeline parameters there are
# too many for them to be a command line argument.
# some of the features are not fully developed yet.
frames:
  return_denoized: true
  disk_size: 2
  invert: false
masks:
  levels: 4
tracking:
  min_value: 10
  normalize: true
  reference_frame: 0
calculate:
  remove_background: true
  fill_holes: false
  min_size: 20000
  attributes:
    - area
    - bbox_area
    - convex_area
    - eccentricity
    - extent
    - local_centroid
    - major_axis_length
    - minor_axis_length
    - perimeter
    - solidity
    - weighted_local_centroid
  cache: true
video:
  write: true
  what:
    - overlay
    - mask
    - frame
  periodicity: 20
  FPS: 10
  size:
    width: 3
    height: 3