# there are two examples here one for background subtraction the other for
# optical flow, only one can be used at any given time
# see objcet_config.yaml and readme for video parsing and output options
# a full list of acceptable parameters can be found in readme


# background subtraction
method: movement_detection # see readme for details and mandatory fields
type: background_subtraction
algorithm: MOG2
algorithm_params:
  varThreshold: 20 # see readme for method specific parameters

# dense optical flow
method: movement_detection
type: optical_flow
algorith:
  name: farnebeck
  params:
    numLevels: 5 # see readme for a full list
    winSize: 20
  return: magnitude
