# video processing parameters you don't have to include there see readme for default and
# mandatory parameters
video:
  invert: false
  denoise: true
  disk: 2
  adjust:
    method: gamma
    gain: 1 #this is a gamma specific parameter see readme for details
  normalize: true
  reference_frame: 0 # if normalize is false this parameter is ignored

# analysis parameters
method: object_detection
threshold:
  algorihtm: otsu
  algorithm_params: # add method specific parameters here see readme for details
    nbins: 255
segmentation_params: # add watershed specific parameters here
  compactness: 2

cores: 1 #this is used for both segmentation and feature calculation

calculate: # see readme for all available options
  properties: # see readme for a complete list
    - area
    - bbox_area
    - convex_area
    - eccentricity
  cache: true
  fill_holes: false
  get_largest: true

# video output parameters
video_output:
  write: true # if this is false the rest is ignored see readme
  what:
    - mask
    - frame #using pseudo color
  periodicity: 10 # use every nth frame
  FPS: 10 #frames per second
  size:
    width: 3 #inches
    height: 3

